import React, { useState } from 'react';
import { Container, Form, Button, Row, Col } from 'react-bootstrap';
import './Contact.css';

export default function Contact() {
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });
  const handleSubmit = (e) => { e.preventDefault(); const subject = encodeURIComponent('Portfolio Contact'); const body = encodeURIComponent(`Name: ${formData.name}\nEmail: ${formData.email}\n\nMessage:\n${formData.message}`); window.location.href = `mailto:ragavinayds@gmail.com?subject=${subject}&body=${body}`; };
  return <Container className="contact-container"><div className="section-heading"><p className="section-eyebrow">05 — Contact</p><h2 className="contact-title">Let&apos;s build<br />something useful.</h2><p className="contact-subtitle">I&apos;m open to internships, collaborations, and opportunities where hardware and software meet.</p></div><Row><Col lg={7}><div className="contact-card"><Form onSubmit={handleSubmit} className="contact-form"><Form.Group className="mb-4"><Form.Label className="form-label">Name</Form.Label><Form.Control type="text" name="name" value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} required className="form-control-custom" placeholder="Your name" /></Form.Group><Form.Group className="mb-4"><Form.Label className="form-label">Email</Form.Label><Form.Control type="email" name="email" value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} required className="form-control-custom" placeholder="you@example.com" /></Form.Group><Form.Group className="mb-4"><Form.Label className="form-label">Message</Form.Label><Form.Control as="textarea" rows={5} name="message" value={formData.message} onChange={(e) => setFormData({ ...formData, message: e.target.value })} required className="form-control-custom" placeholder="Tell me about the opportunity..." /></Form.Group><Button className="contact-btn" type="submit">Send message ↗</Button></Form></div></Col><Col lg={5} className="contact-side"><p className="contact-side-label">Direct contact</p><a href="mailto:ragavinayds@gmail.com" className="contact-direct">ragavinayds@gmail.com</a><p className="contact-location">Bengaluru, India<br />+91 99892 35824</p></Col></Row></Container>;
}
